lore:
  Usage: 'Place this block on the ground, then punch it to activate the fuse. You will have a couple of seconds before it explodes. To defuse and pick up a placed TNT block, break it with shears.'
types:
  mining:
    DisplayName: Mining Dynamite
    Id: 97a0f14d-8c68-4050-b710-60c11812d760
    Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzRkN2ZjOGUzYTk1OWFkZTdkOWNmNjYzZjFlODJkYjc5NzU1NDNlMjg4YWI4ZDExZWIyNTQxODg4MjEzNTI2In19fQ==
    Description: 'The favorite of all blast mining experts. This type of TNT will only remove the lesser valuable blocks from under ground. All your valuable ores will remain intact, but revealed for you to mine with your professional tools.'
    Yield: 16
  woodcutting:
    DisplayName: Lumber Bomb
    Id: 0162e6e9-aded-4fa5-b5be-dbea25cf2a9b
    Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGEzZDVkNWIyY2YzMzEyOTllNjNkNzYxOGExNDI2NmU4Y2NjNjE1OGU5ZTMxZmNiMGJkOTExZTEyZmY3NzM2In19fQ==
    Description: 'Lumberjack''s best friend. This explosive will break all sorts of logs and leaves, but nothing else. Nothing is more precise and efficient in removing large sections of trees!'
    Yield: 16
  nuke:
    DisplayName: Neutron Bomb
    Id: 206a8059-f5fb-41e7-8b33-233b5c72f932
    Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2ZhZjNlZmJmZjZkN2VmNDY1ZWNhY2JjNTE3ZjRkYWQ1Y2MxYTIyNjFlYTdhNjA5ZjIxNmFhZTQ4Nzg0In19fQ==
    Description: 'The neutron bomb will destroy all kinds of foliage, including grass, which turns to wasteland. Be wary of its wide explosion radius.'
    Yield: 32
  silk:
    DisplayName: Silk Charge
    Id: 30a55204-8ae8-476e-803f-97324e627391
    Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmNlNmQ4MjE4NmEzNzdmNTQzNWU5ODZkMWY5NmIwNDY5MTk3MTM4NjFiYmJiZGVlMzBlYWRiODMxYzI0In19fQ==
    Description: 'Break blocks such as ores, stone, glass, and some others, as if they were broken with a silk touch pickaxe.'
    Yield: 4
  kinetic:
    DisplayName: Kinetic Blast
    Id: 685c5a22-6aeb-4392-a59a-6d6e0d611221
    Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDFkNDc5MWYzYjlhNWVhNGJmYWFkY2Q3NzliNTE2NDJkNDkzMGEyMzU5OWI5MzQ3YTMzNzVkM2IyNzIxZCJ9fX0=
    Description: 'Catapult blocks into the air instead of breaking them.'
    Yield: 4
  power:
    DisplayName: Power TNT
    Id: cb9bc04e-23bf-4ac0-a7d4-38ddda0e8d97
    Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjM5NWQzN2Y4ODg1MTEzZmI3ZmNiOGY1YzYxNzQ1MjAxYmVmZjk5MWZiZDUyYWM1ZmZkNzkxYTkwNTZkNiJ9fX0=
    Description: 'This powerful charge has significantly more explosive potential than its vanilla counterpart.'
    Yield: 16