lore:
  Usage: 'Place this block on the ground, then punch it to activate the fuse. You will have a couple of seconds before it explodes.'
tnt_types:
  mining:
    DisplayName: Mining Dynamite
    Id: 97a0f14d-8c68-4050-b710-60c11812d760
    Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzRkN2ZjOGUzYTk1OWFkZTdkOWNmNjYzZjFlODJkYjc5NzU1NDNlMjg4YWI4ZDExZWIyNTQxODg4MjEzNTI2In19fQ==
    Description: 'The favorite of all blast mining experts. This type of TNT will only remove the lesser valuable blocks from under ground. All your valuable ores will remain intact, but revealed for you to mine with your professional tools.'
  woodcutting:
    DisplayName: Lumber Bomb
    Id: 0162e6e9-aded-4fa5-b5be-dbea25cf2a9b
    Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGEzZDVkNWIyY2YzMzEyOTllNjNkNzYxOGExNDI2NmU4Y2NjNjE1OGU5ZTMxZmNiMGJkOTExZTEyZmY3NzM2In19fQ==
    Description: 'Lumberjack''s best friend. This explosive will break all sorts of logs and leaves, but nothing else. Nothing is more precise and efficient in removing large sections of trees!'
